import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { InventoryItem } from '../models/inventory.model';

export interface InventoryExportMeta {
  branchName?: string;
  generatedBy?: string;
  filtersSummary?: string;
}

const BRAND_GREEN: [number, number, number] = [20, 184, 165];   // --color-brand-primary
const BRAND_DEEP: [number, number, number]  = [9, 82, 74];       // --color-brand-deep
const TEXT_MUTED: [number, number, number]  = [100, 116, 139];

/** Draws the little pharmacy "plus in a diamond" mark used in the app sidebar,
 *  reproduced with plain vector shapes so no external logo asset is needed. */
function drawDawavaMark(doc: jsPDF, x: number, y: number, size: number): void {
  doc.setFillColor(...BRAND_GREEN);
  doc.roundedRect(x, y, size, size, size * 0.22, size * 0.22, 'F');
  doc.setFillColor(255, 255, 255);
  const barW = size * 0.14;
  const barL = size * 0.56;
  // horizontal bar
  doc.rect(x + (size - barL) / 2, y + (size - barW) / 2, barL, barW, 'F');
  // vertical bar
  doc.rect(x + (size - barW) / 2, y + (size - barL) / 2, barW, barL, 'F');
}

function drawHeader(doc: jsPDF, title: string, meta: InventoryExportMeta): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;
  let cursorY = 34;

  drawDawavaMark(doc, marginX, cursorY - 16, 22);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...BRAND_DEEP);
  doc.text('Dawava', marginX + 30, cursorY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Pharmacy Management System', marginX + 30, cursorY + 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(title, pageWidth - marginX, cursorY - 2, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  const generatedAt = new Date().toLocaleString();
  doc.text(`Generated: ${generatedAt}`, pageWidth - marginX, cursorY + 12, { align: 'right' });
  if (meta.branchName) {
    doc.text(`Branch: ${meta.branchName}`, pageWidth - marginX, cursorY + 24, { align: 'right' });
  }

  cursorY += 30;
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(1.2);
  doc.line(marginX, cursorY, pageWidth - marginX, cursorY);

  if (meta.filtersSummary) {
    cursorY += 14;
    doc.setFontSize(8.5);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(meta.filtersSummary, marginX, cursorY);
  }

  return cursorY + 12;
}

function drawFooter(doc: jsPDF, pageNumber: number, pageCount: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 40;
  const y = pageHeight - 24;

  doc.setDrawColor(220, 226, 233);
  doc.setLineWidth(0.6);
  doc.line(marginX, y - 10, pageWidth - marginX, y - 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Generated by Dawava Pharmacy System', marginX, y);
  doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - marginX, y, { align: 'right' });
}

/** Builds a printable PDF inventory report with a branded header repeated on
 *  every page and a footer showing page numbers. */
export function exportInventoryPdf(items: InventoryItem[], meta: InventoryExportMeta = {}): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });

  const rows = items.map(item => [
    item.medicineName,
    item.variantName,
    item.barcode || '—',
    item.status,
    item.quantity.toLocaleString(),
    `${item.price.toFixed(2)} ${item.currencyCode}`,
    new Date(item.lastUpdatedAt).toLocaleDateString(),
  ]);

  autoTable(doc, {
    head: [['Medicine', 'Variant', 'Barcode / SKU', 'Status', 'Qty', 'Price', 'Last Updated']],
    body: rows,
    startY: 80,
    margin: { top: 80, left: 40, right: 40, bottom: 40 },
    styles: { fontSize: 8.5, cellPadding: 6 },
    headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [244, 249, 248] },
    didDrawPage: () => {
      drawHeader(doc, 'Inventory Report', meta);
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, i, pageCount);
  }

  doc.save(`dawava-inventory-${new Date().toISOString().slice(0, 10)}.pdf`);
}

/** Builds an .xlsx workbook of the current inventory list. */
export function exportInventoryExcel(items: InventoryItem[], meta: InventoryExportMeta = {}): void {
  const rows = items.map(item => ({
    'Medicine Name': item.medicineName,
    'Variant': item.variantName,
    'Barcode / SKU': item.barcode,
    'Status': item.status,
    'Quantity': item.quantity,
    'Price': item.price,
    'Currency': item.currencyCode,
    'Source': item.source,
    'Last Updated': new Date(item.lastUpdatedAt).toLocaleString(),
  }));

  const worksheet = XLSX.utils.json_to_sheet(rows);
  worksheet['!cols'] = [
    { wch: 28 }, { wch: 22 }, { wch: 18 }, { wch: 12 },
    { wch: 10 }, { wch: 10 }, { wch: 10 }, { wch: 14 }, { wch: 20 },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Inventory');

  if (meta.branchName || meta.filtersSummary) {
    const infoRows = [
      ['Dawava Pharmacy System — Inventory Report'],
      [`Generated: ${new Date().toLocaleString()}`],
      ...(meta.branchName ? [[`Branch: ${meta.branchName}`]] : []),
      ...(meta.filtersSummary ? [[meta.filtersSummary]] : []),
    ];
    const infoSheet = XLSX.utils.aoa_to_sheet(infoRows);
    XLSX.utils.book_append_sheet(workbook, infoSheet, 'Info');
  }

  XLSX.writeFile(workbook, `dawava-inventory-${new Date().toISOString().slice(0, 10)}.xlsx`);
}
